# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_de_naissance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='profil',
            field=models.FileField(default='0.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profil',
            name='sexe',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='profil',
            name='telephone',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterField(
            model_name='profil',
            name='about',
            field=models.TextField(default=None),
        ),
    ]
