# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0002_auto_20170902_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='date_de_naissance',
            field=models.DateField(auto_now_add=True),
        ),
    ]
