# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0003_auto_20170902_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
