# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0004_auto_20170902_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='date_de_naissance',
            field=models.DateField(),
        ),
    ]
