# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0005_auto_20170903_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='date_de_naissance',
            new_name='naissance',
        ),
    ]
