# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ralphlaa', '0007_auto_20170903_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil',
            field=models.FileField(upload_to='Profil'),
        ),
    ]
