# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20170814_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
