# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20170817_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
