# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0010_publication_tst'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='userr',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
